name: Daily Weather Data Automation

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  fetch-weather-data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Execute the weather.sh script
    - name: Run weather.sh
      run: |
        chmod +x weather.sh
        ./weather.sh

    # Step 3: Commit and Push Changes
    - name: Commit and Push Changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/weather/
        git commit -m "Daily weather data update: $(date)"
        git push https://x-access-token:${GH_TOKEN}@github.com/LilianaMPereira/COMPUTER_INFRASTRUCTURE.git HEAD:main
